### ISSUE TITLE
Improve "Enter World" workflow when creating new app

### ISSUE THREAD

**Issue by eddiemg10** [Arttribute/imagine-kit#88]
Currently, it just takes you to a blank screen as shown below

![image](https://github.com/user-attachments/assets/b4a185e1-14b6-4f9c-9f06-aaa89e989429)

Would be nice if it took you straight to the 'edit  world' screen v
![image](https://github.com/user-attachments/assets/f3657f7c-18a4-427c-b5d9-cb8d9b128e51)

Alternatively, maybe a 'tutorial-like workflow' like this
![image](https://github.com/user-attachments/assets/02bf56d8-1ef6-4b02-9b07-ee4d849282c2)

**Comment by bashybaranaba** [comment]
It's supposed to take you to the edit page directly, but there was a small bug. The idea is that if the current username stored in the session after signing in does not match the username in the /uname/worlds/id/edit URL it redirects you to  /uname/worlds/id. The problem was that in the Create world, it was redirecting to the user's full name instead of their username which is why it went directly to the world page. 

This has been fixedd here:[ c46a398f71b4f75c6755a177eea1ed473ad6eed0](https://github.com/Arttribute/imagine-kit/commit/c46a398f71b4f75c6755a177eea1ed473ad6eed0)

**Comment by eddiemg10** [comment]
Noice
